<?php

namespace ClubBundle\Repository;

/**
 * AffecterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffecterRepository extends \Doctrine\ORM\EntityRepository
{
}
