<?php

namespace RHBundle\Repository;

/**
 * CondidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondidatRepository extends \Doctrine\ORM\EntityRepository
{
}
