<?php

namespace ExamenBundle\Repository;

/**
 * Calandrier_exRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Calandrier_exRepository extends \Doctrine\ORM\EntityRepository
{
}
